openapi: "3.0.0"
info:
  description: "Japan Impact's file uploads API"
  version: "1.0.0"
  title: "JI Uploads"
servers:
  - url: "https://api.japan-impact.ch/uploads"
tags:
  - name: "containers"
    description: "Management of file containers"
  - name: "files"
    description: "Management of files in containers"
  - name: "delegation"
    description: "Delegate read-access to containers"
paths:
  /files/{ticket}:
    put:
      tags: ["files"]
      summary: "Submit a file"
      description: "Call this endpoint to submit a file directly. Authentication is optional."
      operationId: "putFile"
      security:
        - api_key: []

    post:
      tags: ["files"]
      summary: "Submit a file"
      description: "Call this endpoint to submit a file via a form. Authentication is optional."
      operationId: "postFile"
      security:
        - api_key: []
  /files/{app}/{container}:
    get:
      tags: ["files"]
      summary: "List all files in a container"
      operationId: "listFiles"
      security:
        - api_key: ["uploads/files/:app/list"]
        - delegation: []
    post:
      tags: ["files"]
      summary: "Create a new upload request"
      description: "Create a new upload request in specified container. This can only be called by APP tokens."
      operationId: "startUpload"
      security:
        - api_key: ["uploads/requests/:app/new"]
  /files/{app}/{container}/{principal}:
    get:
      tags: ["files"]
      summary: "List all files in a container uploaded by a given principal."
      description: "A given principal can ALWAYS access to the list of files it uploaded (simply use its token in the Authentication header)."
      operationId: "listUserFiles"
      security:
        - api_key: ["uploads/files/:app/list"]
        - delegation: []
  /uploadRequests/{ticket}:
    get:
      tags: ["files"]
      summary: "Get the status of an upload request."
      operationId: "uploadRequestStatus"
      security:
        - api_key: ["uploads/files/:app/status"]
  /delegation:
    post:
      tags: ["delegation"]
      summary: "Create a delegation token."
      description: "Creates a token that delegates the permission to read the files in a container. This token will have to be presented in the `Session` header for the requests that need this authorization."
      operationId: "createDelegation"
      security:
        - api_key: ["uploads/files/:app/list/:container"]
  /containers/{app}:
    get:
      tags: ["containers"]
      summary: "List containers belonging to an app."
      operationId: "getContainers"
      security:
        - api_key: ["uploads/containers/:app/get/*"]
    post:
      tags: ["containers"]
      summary: "Create a new container."
      operationId: "createContainer"
      security:
        - api_key: ["uploads/containers/:app/create"]
  /containers/{app}/{container}:
    get:
      tags: ["containers"]
      summary: "Get a container."
      operationId: "getContainer"
      security:
        - api_key: ["uploads/containers/:app/get/:container"]
    put:
      tags: ["containers"]
      summary: "Update a container."
      operationId: "updateContainer"
      security:
        - api_key: ["uploads/containers/:app/update/:container"]
    delete:
      tags: ["containers"]
      summary: "Delete a container and its files."
      operationId: "deleteContainer"
      security:
        - api_key: ["uploads/containers/:app/delete/:container"]
components:
  securitySchemes:
    api_key:
      type: http
      scheme: bearer
      bearerFormat: JWT
    delegation:
      type: apiKey
      in: header
      name: Session
      description: "A JWT delegating read access to some containers to an unauthenticated user"